name: poder lanzarlo desde gitHub
on: 
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Hello, World!"